version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
    environment:
      - DATABASE_URL=sqlite:///app/data/database.sqlite
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local